# This job listens for newly pushed tags. For each found tag, it will will
# do a static build, create a release, and upload said binary to the new
# release's assets.

name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install required rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true

    - name: Build statically linked vmtest
      run: |
        RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
        cp ./target/x86_64-unknown-linux-gnu/release/vmtest ./vmtest-amd64

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        generate_release_notes: true
        files: ./vmtest-amd64
