# This job listens for new releases and will build + upload a statically
# linked vmtest binary to the new release's assets.

name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install required rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
        components: rustfmt, clippy

    - name: Build statically linked vmtest
      run: RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu

    - name: Upload freshly built kernels
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp ./target/x86_64-unknown-linux-gnu/release/vmtest ./vmtest-amd64
        gh release upload ${{ github.ref_name }} ./vmtest-amd64
